apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: https://helm.min.io/
    chart: minio
    targetRevision: 8.0.10
    helm:
      parameters:
        - name: mode
          value: standalone
        - name: replicas
          value: "1"
        - name: auth.existingSecret
          value: minio
        - name: auth.rootUserSecretKey
          value: root-user
        - name: auth.rootPasswordSecretKey
          value: root-password
      timeout: 300

  destination:
    server: https://kubernetes.default.svc
    namespace: data-storage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
