
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 17.0.21
    helm:
      valueFiles:
        - $values/helm-values/minio-values.yaml
      timeout: 300
  - repoURL: https://github.com/tobiasfuhge/data-engineering.git
    targetRevision: main
    ref: values
    
  destination:
    server: https://kubernetes.default.svc
    namespace: data-storage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
