apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    chart: minio
    repoURL: https://charts.min.io/
    targetRevision: 5.0.0
    helm:
      values: |
        mode: standalone
        replicas: 1
        # Hier wird dein Secret eingebunden
        auth:
          existingSecret: "minio"
          rootUserSecretKey: "root-user"
          rootPasswordSecretKey: "root-password"
        persistence:
          enabled: true
          size: 10Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true